[theme]
primaryColor = "#0066CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
